name: Lokalise Key Push
description: 'Pushes new translations keys to Lokalise'
inputs:
  api-token:
    description: API token
    required: true
  project-id:
    description: The project ID
    required: true
  directory:
    description: The directory to find language files
    required: true
  file-extension:
    description: The file extension to look for
    default: json
  key-name-property:
    description: The Lokalise platform to use when comparing key names
    default: web
  platforms:
    description: The platforms where new keys should be pushed
    default: ios android web other
  languages:
    description: The languages used
    required: true
  format:
    description: The file format
    default: json
    
runs:
  using: 'node12'
  main: 'index.js'